
HEADERS = src/aa_xpm.h \
          src/application.h \
          src/arrow.h \
          src/arrows.h \
          src/atom.h \
          src/biotools.h \
          src/bondedit.h \
          src/bond.h \
          src/boshcp.h \
          src/bracket.h \
          src/brackets.h \
          src/CDXConstants.h \
          src/cdxml_reader.h \
          src/charsel.h \
          src/chemdata.h \
          src/colorbutton.h \
          src/clipboard.h \
          src/cml.h \
          src/crings_dialog.h \
          src/cubicbezier.h \
          src/curvearrow.h \
          src/defs.h \
          src/dpoint.h \
          src/drawable.h \
          src/fixeddialog.h \
          src/gobject.h \
          src/graphdata.h \
          src/graphdialog.h \
          src/graphwidget.h \
          src/helpwindow.h \
          src/http.h \
          src/ioiface.h \
          src/justifytools.h \
          src/lines.h \
          src/magnifytools.h \
          src/moldata.h \
          src/molecule.h \
          src/molecule_sssr.h \
          src/molinfodialog.h \
          src/myfiledialog.h \
          src/na_xpm.h \
          src/netaccess.h \
          src/netchoosedialog.h \
          src/netdialog.h \
          src/ngw.h \
          src/pagesetupdialog.h \
          src/paintable.h \
          src/peak.h \
          src/peptidebuilder.h \
          src/previewwidget.h \
          src/render2d.h \
          src/renderarea.h \
          src/ringdialog.h \
          src/ring.h \
          src/rings.h \
          src/ring_xpm.h \
          src/sdg.h \
          src/setofrings.h \
          src/smilesdialog.h \
          src/sorf.h \
          src/sugar_xpm.h \
          src/symbol.h \
          src/symbol_xpm.h \
          src/text.h \
          src/textshapedialog.h \
          src/tool_13c_nmr.h \
          src/tool_1h_nmr.h \
          src/tool_2d3d.h \
          src/tooldialog.h \
          src/tool_ir.h \
          src/xdc_event.h \
          src/xdc_textedit.h \
          src/xdc_toolbutton.h \
          src/xml_cml.h \
          src/xml_reader.h \
          src/xruler.h \
          src/prefs.h \
          src/dyk.h

SOURCES = src/application.cpp \
          src/application_ob.cpp \
          src/application_ring.cpp \
          src/arrow.cpp \
          src/biotools.cpp \
          src/bond.cpp \
          src/bondedit.cpp \
          src/boshcp.cpp \
          src/bracket.cpp \
          src/cdx2cdxml.cpp \
          src/cdxml_reader.cpp \
          src/charsel.cpp \
          src/chemdata_cdx.cpp \
          src/chemdata_cdxml.cpp \
          src/chemdata_cml.cpp \
          src/chemdata.cpp \
          src/chemdata_edit.cpp \
          src/chemdata_event.cpp \
          src/chemdata_mdl.cpp \
          src/chemdata_rw.cpp \
          src/chemdata_rxn.cpp \
          src/chemdata_tools.cpp \
          src/chemdata_xdc.cpp \
          src/chemdata_xml.cpp \
          src/colorbutton.cpp \
          src/crings_dialog.cpp \
          src/curvearrow.cpp \
          src/drawable.cpp \
          src/fixeddialog.cpp \
          src/gobject.cpp \
          src/graphdialog.cpp \
          src/graphwidget.cpp \
          src/helpwindow.cpp \
          src/http.cpp \
          src/ioiface.cpp \
          src/main.cpp \
          src/molecule_1h_nmr.cpp \
          src/molecule.cpp \
          src/molecule_obmol.cpp \
          src/molecule_smiles.cpp \
          src/molecule_sssr.cpp \
          src/molecule_tools_1.cpp \
          src/molecule_tools_2.cpp \
          src/molinfodialog.cpp \
          src/myfiledialog.cpp \
          src/netaccess.cpp \
          src/netchoosedialog.cpp \
          src/netdialog.cpp \
          src/ngw.cpp \
          src/pagesetupdialog.cpp \
          src/peptidebuilder.cpp \
          src/previewwidget.cpp \
          src/render2d.cpp \
          src/render2d_draw.cpp \
          src/render2d_event.cpp \
          src/render2d_print.cpp \
          src/render2d_select.cpp \
          src/render2d_text.cpp \
          src/renderarea.cpp \
          src/retro.cpp \
          src/ringdialog.cpp \
          src/smilesdialog.cpp \
          src/symbol.cpp \
          src/text.cpp \
          src/textshapedialog.cpp \
          src/to3d.cpp \
          src/tool_13c_nmr.cpp \
          src/tool_1h_nmr.cpp \
          src/tool_2d3d.cpp \
          src/tooldialog.cpp \
          src/tool_ir.cpp \
          src/xdc_toolbutton.cpp \
          src/xml_cml.cpp \
          src/xml_reader.cpp \
          src/xruler.cpp \
          #src/userpreferences.cpp \
          src/dyk.cpp

TRANSLATIONS = \
    translation/xdrawchem_da.ts \
    translation/xdrawchem_dk.ts \
    translation/xdrawchem_es.ts \
    translation/xdrawchem_it.ts \
    translation/xdrawchem_nl.ts \
    translation/xdrawchem_pt_BR.ts \
    translation/xdrawchem_de.ts \
    translation/xdrawchem_en.ts \
    translation/xdrawchem_fr.ts \
    translation/xdrawchem_jp.ts \
    translation/xdrawchem_pl.ts \
    translation/xdrawchem_pt.ts
